server:
  port: 8050

spring:
  application:
    name: kaldar

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kaldar_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:122024Clux!}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from-name: "Kaldar"
    from-email: ${MAIL_USERNAME}

  config:
    import: classpath:secret.yml

security:
  otp:
    digit: ${OTP_DIGIT:6}
    expiry-minutes: ${OTP_EXPIRATION:1}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
