package com.kaldar.kaldar.payment.infrastructure.payment;

import com.kaldar.kaldar.shared.domain.exceptions.PaymentProcessingException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

/**
 * Low-level HTTP adapter for the Paystack REST API.
 *
 * <p>Responsibilities:</p>
 * <ul>
 *   <li>Sign every request with the Bearer secret key</li>
 *   <li>Convert NGN amounts to kobo before sending (Paystack works in smallest currency unit)</li>
 *   <li>Throw {@link IllegalStateException} if Paystack returns a non-success response</li>
 * </ul>
 *
 * <p>Configuration (application.yml):</p>
 * <pre>
 * paystack:
 *   secret-key: ${PAYSTACK_SECRET_KEY:}
 *   base-url: https://api.paystack.co
 * </pre>
 */
@Component
public class PaystackClient {

    private static final Logger log = LoggerFactory.getLogger(PaystackClient.class);

    private final RestTemplate restTemplate;
    private final String secretKey;
    private final String baseUrl;

    public PaystackClient(
            @Value("${paystack.secret-key:}") String secretKey,
            @Value("${paystack.base-url:https://api.paystack.co}") String baseUrl) {
        this.secretKey = secretKey;
        this.baseUrl = baseUrl;
        this.restTemplate = new RestTemplate();
    }

    /**
     * Calls {@code POST /transaction/initialize} on the Paystack API.
     *
     * @param email     the customer's email address (displayed on Paystack checkout)
     * @param amountNgn the amount in Naira — converted to kobo internally
     * @param reference the unique transaction reference generated by our system
     * @return parsed {@link PaystackInitData} containing the authorization URL
     * @throws IllegalStateException if Paystack returns an error or the call fails
     */
    public PaystackInitData initializeTransaction(String email, BigDecimal amountNgn, String reference) {
        HttpHeaders headers = buildAuthHeaders();

        Map<String, Object> body = new HashMap<>();
        body.put("email", email);
        body.put("amount", toKobo(amountNgn));
        body.put("reference", reference);
        body.put("currency", "NGN");

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(body, headers);

        try {
            ResponseEntity<PaystackApiResponse> response = restTemplate.exchange(
                    baseUrl + "/transaction/initialize",
                    HttpMethod.POST,
                    request,
                    PaystackApiResponse.class
            );

            PaystackApiResponse apiResponse = response.getBody();
            if (apiResponse == null || !apiResponse.isStatus()) {
                String errorMessage = apiResponse != null ? apiResponse.getMessage() : "no response body";
                log.error("Paystack initialization failed for reference {}: {}", reference, errorMessage);
                throw new PaymentProcessingException("Paystack payment initialization failed: " + errorMessage);
            }

            log.info("Paystack transaction initialized successfully. Reference: {}", reference);
            return apiResponse.getData();

        } catch (RestClientException ex) {
            log.error("HTTP error calling Paystack /transaction/initialize for reference {}", reference, ex);
            throw new PaymentProcessingException("Unable to reach Paystack payment gateway. Please try again later.");
        }
    }

    // ─── Private helpers ──────────────────────────────────────────────────────

    private HttpHeaders buildAuthHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(secretKey);
        return headers;
    }

    /**
     * Converts a Naira amount to kobo (smallest currency unit).
     * Paystack requires amounts in kobo (1 NGN = 100 kobo).
     */
    private long toKobo(BigDecimal amountNgn) {
        return amountNgn.multiply(BigDecimal.valueOf(100)).longValue();
    }
}
